version: "3"
services:
  web:
    image: node:14
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - sql-server
    networks:
      - app-network

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
      SA_PASSWORD: YourPassword123!
      ACCEPT_EULA: Y
    volumes:
      - sql_data:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - sql-server
    networks:
      - app-network
    environment:
      SQL_SERVER_HOST: sql-server
      SQL_SERVER_PORT: 1433
      SQL_SERVER_DATABASE: TaskManagerDB
      SQL_SERVER_USER: sa
      SQL_SERVER_PASSWORD: YourPassword123!

networks:
  app-network:
    driver: bridge

volumes:
  sql_data:
